### ISSUE TITLE
run error : run_sst2_classification.py

### ISSUE THREAD

**Issue by fangd123** [raymondzmc/T3-Vis#1]
run command: `CUDA_VISIBLE_DEVICES=-1  python run_sst2_classification.py --model bert_classifier --train_set sst2_train_set --validation_set sst2_validation_set --validation_set sst2_test_set`

it says:
```bash
Traceback (most recent call last):
  File "run_sst2_classification.py", line 250, in <module>
    main(args)
  File "run_sst2_classification.py", line 70, in main
    importance = compute_importance(model, val_dataloader)
  File "/home/hmqf/projects/T3-Vis/application/utils/head_importance.py", line 95, in compute_importance
    output = model(**inputs)
  File "/home/hmqf/anaconda3/envs/hmqf_dl_38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hmqf/anaconda3/envs/hmqf_dl_38/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1564, in forward
    loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
  File "/home/hmqf/anaconda3/envs/hmqf_dl_38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hmqf/anaconda3/envs/hmqf_dl_38/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/hmqf/anaconda3/envs/hmqf_dl_38/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target -1 is out of bounds.
```

**Comment by fangd123** [comment]
my fault , sorry
